testPath: dataSourcing/scrapperTestCases/
1646849: dataSourcing/scrapperTestCases/1646849
2973707: dataSourcing/scrapperTestCases/2973707
2973737: dataSourcing/scrapperTestCases/2973737
2973782: dataSourcing/scrapperTestCases/2973782
2979515: dataSourcing/scrapperTestCases/2979515
htmlParser: dataSourcing/scrapperTestCases/htmlParser
scrapedData: dataSourcing/scrapperTestCases/scrapedData
downloadData: 31-12-2021